name: ltxbot
version: 0.1.0
synopsis: Twitter Bot turning LaTeX tweets into PNGs
description:
  A Twitter bot that listens for mentions and replies with an image of the Tweet
  interpreted as LaTeX. The image is rendered in a Docker container that is
  spawned on every incoming mention. Possibly not race-condition-proof.
homepage: https://github.com/passy/ltxbot
license: MIT
author: Pascal Hartig
maintainer: Pascal Hartig <phartig@rdrei.net>
category: Web
extra-source-files:
  - stack.yaml
  - README.markdown

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fwarn-incomplete-record-updates
  - -fwarn-monomorphism-restriction
  - -fwarn-unused-do-bind

dependencies:
  - base >= 4.7 && < 5
  - text

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - ltxbot
      - twitter-conduit >= 0.2.1
      - twitter-types
      - twitter-types-lens
      - HaTeX
      - mtl
      - network-uri
      - containers
      - case-insensitive
      - lens >=4.0
      - lens-action
      - transformers-base
      - monad-logger
      - authenticate-oauth >=1.4
      - bytestring >=0.10
      - conduit >= 1.0
      - configurator >= 0.2
      - exceptions >= 0.5
      - http-conduit >= 2.0
      - resourcet >= 0.4
      - text >= 1.1
      - transformers >= 0.3
      - temporary
      - filepath
      - process
      - hspec
      - time
      - aeson

library:
  source-dirs: src
  ghc-options:
    - -Wall
  dependencies:
    - HaTeX
    - authenticate-oauth >=1.4
    - bytestring >=0.10
    - case-insensitive
    - cmdargs >= 0.10
    - conduit >= 1.0
    - configurator >= 0.2
    - containers
    - exceptions >= 0.5
    - filepath
    - http-conduit >= 2.0
    - lens >= 4.0
    - lens-action
    - monad-logger
    - mtl
    - network-uri
    - process
    - resourcet >= 0.4
    - temporary
    - transformers >= 0.3
    - transformers-base
    - twitter-conduit >= 0.2.1
    - twitter-types
    - twitter-types-lens
    - aeson
    - time
  exposed-modules:
    - Web.Twitter.LtxBot
    - Web.Twitter.LtxBot.Common
    - Web.Twitter.LtxBot.Latex
    - Web.Twitter.LtxBot.Types

executables:
  disruption-tracker:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - ltxbot
      - HaTeX
      - authenticate-oauth >=1.4
      - bytestring >=0.10
      - case-insensitive
      - cmdargs >= 0.10
      - conduit >= 1.0
      - configurator >= 0.2
      - containers
      - exceptions >= 0.5
      - filepath
      - http-conduit >= 2.0
      - lens >= 4.0
      - lens-action
      - monad-logger
      - mtl
      - network-uri
      - process
      - resourcet >= 0.4
      - temporary
      - transformers >= 0.3
      - transformers-base
      - twitter-conduit
      - twitter-types
      - twitter-types-lens
      - aeson
      - time
