flags: {}
packages:
- '.'
extra-deps:
- http-client-0.4.31.2
- http-client-tls-0.2.4.1
- http-conduit-2.1.11
- twitter-conduit-0.2.1
- twitter-types-0.7.2.2
- twitter-types-lens-0.7.2
resolver: lts-8.0
